modLoader="javafml"
loaderVersion="[${lang_version},)"
issueTrackerURL="https://github.com/TheCBProject/EnderStorage"
license="The MIT License (MIT)"

[[mods]]
	modId="enderstorage"
	displayName="EnderStorage"
	version="${file.jarVersion}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=EnderStorage&mc=${mc_version}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8"
	authors="ChickenBones, covers1624"
	description='''
Stores your stuff in the END!
    Credits: Ecu - original idea, design, chest and pouch texture
    Rosethorns - tank model
    Soaryn - tank texture
	'''
[[dependencies.enderstorage]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.enderstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.enderstorage]]
    modId="codechickenlib"
    mandatory=true
    versionRange="${ccl_version_range}"
    ordering="AFTER"
    side="BOTH"
